### PR TITLE
Fix some MAP issues

### LINKED ISSUE #365: MAP: StatsBox: cursor on hover should not be hand
logo 

# Problem

# Proposed solution

this area should use the default pointer cursor

### LINKED ISSUE #367: MAP: Light/Dark: default is not consistent
logo 

# Problem

When first loading the page, some components are displayed in Light mode, while others are in Dark mode. They should all be consistent.

**Default (mixed)**

**Dark**

# Proposed solution

This will be a setting that can be changed by querystring, and easily by the user. I think for now let's default everything to Dark as it matches better with the 2.0 WEB version that it'll be embedded in.

### LINKED ISSUE #369: MAP: Light/Dark: change the text of how to toggle
logo 

# Problem

In the TabMenu -> Settings, there is a "botton" with the text `Toggle Dark Mode` 

this text isn't very descriptive to the user

# Proposed solution

Change the text to
`Switch to [opposite] mode` 
where [opposite] is either Light or Dark depending on what the current state is. So if all components are currently light, it would say "Switch to Dark mode" 

# Related issues

* #367
* #368

### PR DESCRIPTION
**Pull request by stanley-miao**
Resolves #365, resolves #367, and resolves #369. Fixes most of #368 except for the final point.

### CODE REVIEW

File: MAP/src/components/TabMenu/TabMenu.js [hunk 1]
```diff
@@ -21,11 +21,11 @@ const renderMenu = (
...
+          return 'Switch to ';
         case 'menu.userPreferenceSection.theme.light':
-          return 'Light mode';
-        case 'menu.userPreferenceSection.theme.dark':
           return 'Dark mode';
+        case 'menu.userPreferenceSection.theme.dark':
+          return 'Light mode';
         default:
           return s;
       }
```
Comment (jeff-knurek) [inline MAP/src/components/TabMenu/TabMenu.js:31]: is this block obsolete? can you try removing it to confirm it all still works?

Comment (stanley-miao) [reply MAP/src/components/TabMenu/TabMenu.js]: `locale` itself needs to be passed to `<Settings>`, but it still works without the function.

**Review by jeff-knurek — APPROVED** [review]
